### ISSUE TITLE
debezium connector failure  in latest kafka-connect-datagen

### ISSUE THREAD

**Issue by gireeshgopinath** [confluentinc/kafka-connect-datagen#32]
For the latest  kafka-connect-datagen having " Creation of database history topic failed " issue when  using debezium connector. configuration are fine and its worked for me before 2 weeks.

"connector":{"state":"RUNNING","worker_id":"connect:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"connect:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Creation of database history topic failed, please create the topic manually\n\tat io.debezium.relational.history.KafkaDatabaseHistory.initializeStorage(KafkaDatabaseHistory.java:360)\n\tat io.debezium.relational.HistorizedRelationalDatabaseSchema.initializeStorage(HistorizedRelationalDatabaseSchema.java:61)\n\tat io.debezium.connector.sqlserver.SqlServerConnectorTask.start(SqlServerConnectorTask.java:94)\n\tat io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:49)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.TimeoutException\n\tat org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)\n\tat io.debezium.relational.history.KafkaDatabaseHistory.getKafkaBrokerConfig(KafkaDatabaseHistory.java:365)\n\tat io.debezium.relational.history.KafkaDatabaseHistory.initializeStorage(KafkaDatabaseHistory.java:339)\n\t... 11 more\n"}],"type":"source"}

recently its worked fine but now its showing this error all the time. Please help....!!!!!!!!

**Comment by gireeshgopinath** [comment]
its solved by setting  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092 to ip address  in **docker-compose yml** file.

**Comment by statiko1** [comment]
@gireeshgopinath 👍 
What worked for you 1 or 2?

1. KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://{ipAddress}:29092,PLAINTEXT_HOST://{ipAddress}:9092

2. KAFKA_ADVERTISED_LISTENERS:{ipAddress}
