### ISSUE TITLE
Use schema of schema.keyfield instead of String

### ISSUE THREAD

**Issue by ryan-carlson** [confluentinc/kafka-connect-datagen#54]
The current implementation always uses String for the key schema regardless of the actual type of the key.  Is there a reason for this design decision?  

I am hoping to use the data generator to produce data matching some of our production topics where we are using Integer keys and Avro values.  This would allow me to simulate a production topic so I can easily develop for downstream connectors or applications.  The existing implementation of data generator does not appear to support this usage due to the fact that it always uses String key but I am expecting Integer.

**Comment by ryan-carlson** [comment]
Here a proposed PR with the changes:  https://github.com/confluentinc/kafka-connect-datagen/pull/55

**Comment by ybyzek** [comment]
@ryan-carlson would it be possible to try the following workaround?  Run `kafka-connect-datagen` with an SMT to cast the key from Integer to String.

About the `cast` SMT: https://docs.confluent.io/current/connect/transforms/cast.html

**Comment by ybyzek** [comment]
@ryan-carlson would it be possible to try the following workaround?  Run `kafka-connect-datagen` with an SMT to cast the key from Integer to String.

About SMTs: https://docs.confluent.io/current/connect/transforms/cast.html

**Comment by ryan-carlson** [comment]
@ybyzek Thank you for sharing the info regarding the workaround.

And I received a commen in my PR that this feature has just been merged and released as part of 0.3.0 version with is great news for me!
