### ISSUE TITLE
"error_code": 500

### ISSUE THREAD

**Issue by kemathur** [confluentinc/kafka-connect-datagen#8]
Hello,

While running the connector I get the following error:

confluent config datagen-pageviews -d connector_pageviews_cos.config

{
  "error_code": 500,
  "message": "Failed to find any class that implements Connector and which name matches io.confluent.kafka.connect.datagen.DatagenConnector, available connectors are: PluginDesc{klass=class io.confluent.connect.elasticsearch.ElasticsearchSinkConnector, name='io.confluent.connect.elasticsearch.ElasticsearchSinkConnector', version='5.0.1', encodedVersion=5.0.1, type=sink, typeName='sink', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka-connect-elasticsearch/'}, PluginDesc{klass=class io.confluent.connect.hdfs.HdfsSinkConnector, name='io.confluent.connect.hdfs.HdfsSinkConnector', version='5.0.1', encodedVersion=5.0.1, type=sink, typeName='sink', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka-connect-hdfs/'}, PluginDesc{klass=class io.confluent.connect.hdfs.tools.SchemaSourceConnector, name='io.confluent.connect.hdfs.tools.SchemaSourceConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka-connect-hdfs/'}, PluginDesc{klass=class io.confluent.connect.jdbc.JdbcSinkConnector, name='io.confluent.connect.jdbc.JdbcSinkConnector', version='5.0.1', encodedVersion=5.0.1, type=sink, typeName='sink', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka-connect-jdbc/'}, PluginDesc{klass=class io.confluent.connect.jdbc.JdbcSourceConnector, name='io.confluent.connect.jdbc.JdbcSourceConnector', version='5.0.1', encodedVersion=5.0.1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka-connect-jdbc/'}, PluginDesc{klass=class io.confluent.connect.s3.S3SinkConnector, name='io.confluent.connect.s3.S3SinkConnector', version='5.0.1', encodedVersion=5.0.1, type=sink, typeName='sink', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka-connect-s3/'}, PluginDesc{klass=class io.confluent.connect.storage.tools.SchemaSourceConnector, name='io.confluent.connect.storage.tools.SchemaSourceConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka-connect-hdfs/'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=sink, typeName='sink', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=connector, typeName='connector', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=sink, typeName='sink', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.0.1-cp1', encodedVersion=2.0.1-cp1, type=source, typeName='source', location='file:/Users/mathurk/other_code/pipeline/kafka/confluent/confluent-5.0.1/share/java/kafka/'}"

**Comment by ybyzek** [comment]
@kemathur : one guess is that the datagen connector jar file hasn't been added to the plugin path.  Have you done this step:

```bash
confluent-hub install confluentinc/kafka-connect-datagen:0.1.0
```

and then restarted Confluent Platform?

**Comment by kemathur** [comment]
I had not restarted. Works after restart. Thanks

**Comment by acmoune** [comment]
How to you restart the confluent platform ?

When I type:

```
confluent local stop
confluent local start
```

Schema registry fail to start.
